name: Build with Visual Studio Developer Command Prompt

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore Nuget packages
        run: nuget restore MyProject.sln

      - name: Build project with MSBuild
        run: msbuild MyProject.sln /p:Configuration=Release

      - name: Kustomize Edit image
        uses: williamhogman/kustomize-set-image-hook@v1.5
        with:
          workingDirectory: .
          kustomizePath: .
          name: my-image
          newTag: latest
          newName: my-image-new
