name: Build with Visual Studio Developer Command Prompt

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Lấy mã nguồn từ Kho Lưu Trữ

      - name: Setup Visual Studio Developer Command Prompt
        uses: egor-tensin/vs-shell@v2 # Thiết lập VS Developer Command Prompt

      - name: Restore Nuget packages
        run: nuget restore MyProject.sln # Khôi phục các package nếu cần

      - name: Build project with devenv
        run: devenv Myproject.sln/Build Release # Biên dịch dự án bằng Visual Studio

      - name: Kustomize Edit image
      # You may pin to the exact commit or the version.
      # uses: williamhogman/kustomize-set-image-hook@c9f7c8ae7aa5ea6224bc39376e8d300d04757068
        uses: williamhogman/kustomize-set-image-hook@v1.5
          with:
          # The path to the working directory
            workingDirectory: # default is .
            # The path to the folder containing the kustomization
            kustomizePath: # default is .
            # Name of the image to replace the image
            name: 
            # The new tag for the named image
            newTag: 
            # 
            newName: 
          
